const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.IsOverObject
	];
};
self.C3_JsPropNameTable = [
	{ФонУ1: 0},
	{Твёрдый: 0},
	{БлокиУ1: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Игрок: 0},
	{СквознаяПлатформа: 0},
	{Синусоида: 0},
	{Спрайт2: 0},
	{Шипы: 0},
	{Ваншот: 0},
	{Якорь: 0},
	{Жизни: 0},
	{Спрайт3: 0},
	{МожетСтрелять: 0},
	{ХпВраг: 0},
	{ЗЕРКАЛО: 0},
	{Пуля: 0},
	{УничтожениеВнеМакета: 0},
	{Враг: 0},
	{Спрайт4: 0},
	{Угасание: 0},
	{ПуляИгрока: 0},
	{Клавиатура: 0},
	{Мышь: 0},
	{Спрайт6: 0},
	{ТекстПатроны: 0},
	{Спрайт7: 0},
	{СтеныВрага: 0},
	{Аудио: 0},
	{Спрайт: 0},
	{переходУровня: 0},
	{ФонУ2: 0},
	{БлокиУ2: 0},
	{a9773c9882d66c4ab70373de13fb1c: 0},
	{БлокиУ3: 0},
	{Прикрепить: 0},
	{Спрайт5: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{бОССКВАДРАТ: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{ХпИгрока: 0},
	{ПулиИгрока: 0},
	{уРОВЕНЬ: 0}
];

self.InstanceType = {
	ФонУ1: class extends self.ITilemapInstance {},
	БлокиУ1: class extends self.ITilemapInstance {},
	Игрок: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Шипы: class extends self.ISpriteInstance {},
	Ваншот: class extends self.ISpriteInstance {},
	Жизни: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Враг: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	ПуляИгрока: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Мышь: class extends self.IInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	ТекстПатроны: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	СтеныВрага: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	переходУровня: class extends self.ISpriteInstance {},
	ФонУ2: class extends self.ITilemapInstance {},
	БлокиУ2: class extends self.ITilemapInstance {},
	a9773c9882d66c4ab70373de13fb1c: class extends self.ISpriteInstance {},
	БлокиУ3: class extends self.ITilemapInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	бОССКВАДРАТ: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {}
}